version: "3.8"
services:
  backend-flask:
    environment:
      FRONTEND_URL: ${FRONTEND_URL}
      BACKEND_URL: ${BACKEND_URL}
    build: ./backend-flask
    ports:
      - "4567:4567"
    volumes:
      - ./backend-flask:/backend-flask
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4567/health"]
      interval: 20s
      timeout: 5s
      retries: 3
  frontend-react-js:
    build: ./frontend-react-js
    environment:
      REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react-js:/frontend-react-js
    depends_on:
      backend-flask: 
        condition: service_healthy
networks: 
  internal-network:
    driver: bridge
    name: cruddur